name: Pipeline Sentinel Test
run-name: Monitoring build for malicious activity

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}:${{ github.sha }}
          docker build -t $IMAGE_ID .
          docker push $IMAGE_ID

  test-with-sentinel:
    needs: build
    runs-on: ubuntu-latest
    services:
      sentinel:
        image: ghcr.io/${{ github.repository }}:${{ github.sha }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        options: >-
          --pid=host
          --cap-add=SYS_ADMIN
          -v /sys/kernel/debug:/sys/kernel/debug:ro

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Run Fake Build Script for Testing
        run: |
          chmod +x ./fake_build_script.sh
          ./fake_build_script.sh || true
      
      - name: Create report directory and artifact
        run: mkdir -p reports

      - run: docker logs ${{ job.services.sentinel.id }} > sentinel-log.txt
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: sentinel-log.txt
      
      - run: |
          cat sentinel-log.txt
          if grep -q "critical" sentinel-log.txt; then
            echo "Build FAILED due to critical alert found in logs."
            exit 1
          else
            echo "Build successful. No critical alerts found."
          fi

